"""Add sharing features and conversation history

Revision ID: 4403eb274720
Revises: 3e868c81455b
Create Date: 2025-08-20 00:56:56.458718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4403eb274720'
down_revision: Union[str, Sequence[str], None] = '3e868c81455b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('shareable_token', sa.String(), nullable=True))
    op.add_column('notebooks', sa.Column('is_public', sa.Boolean(), server_default='f', nullable=False))
    op.create_index(op.f('ix_notebooks_shareable_token'), 'notebooks', ['shareable_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebooks_shareable_token'), table_name='notebooks')
    op.drop_column('notebooks', 'is_public')
    op.drop_column('notebooks', 'shareable_token')
    # ### end Alembic commands ###
