"""add datasources

Revision ID: 8c100c6b6aa7
Revises: c24bcc7d1162
Create Date: 2025-08-20 23:01:25.930743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c100c6b6aa7'
down_revision: Union[str, Sequence[str], None] = 'c24bcc7d1162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('db_type', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('encrypted_password', sa.String(), nullable=True),
    sa.Column('dbname', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_connections_id'), 'data_source_connections', ['id'], unique=False)
    op.create_index(op.f('ix_data_source_connections_name'), 'data_source_connections', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_source_connections_name'), table_name='data_source_connections')
    op.drop_index(op.f('ix_data_source_connections_id'), table_name='data_source_connections')
    op.drop_table('data_source_connections')
    # ### end Alembic commands ###
